/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tayushi1610.ME_QCALC_QA;

public class App {


   public static void main(String[] args) {

       System.out.println("Starting QCalc..");

       StandardCalculator calc = new StandardCalculator();

       calc.add(1, 2);

       System.out.println(calc.getResult());

   }


}
