/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tayushi1610.ME_QCALC_QA;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import com.App;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
